coverage:
  range: 90..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: 100%
        threshold: 0%
        base: auto
comment:
  layout: "header, diff, tree"
  behavior: once
  require_changes: true
